Online-Store/OnlineStore.Cms/Controllers/StockEventController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.BusinessLogic.Service;
using OnlineStore.Cms.Models.Response.Stock;

namespace OnlineStore.Cms.Controllers
{
    public class StockEventController : Controller
    {
        private readonly ILogger<StockEventController> _logger;
        private readonly IStockService _stockService;
        protected IMapper Mapper { get; }

        public StockEventController(
            ILogger<StockEventController> logger,
            IStockService stockService,
            IMapper mapper)
        {
            _logger = logger;
            _stockService = stockService;
            Mapper = mapper;
        }

        // GET: StockEventController
        public async Task<IActionResult> IndexAsync(string? SearchString)
        {
            try
            {
                var result = await _stockService.GetStockEvents(SearchString);
                return View(Mapper.Map<StockEventRes[]>(result));
            }
            catch
            {
                return View();
            }
        }
    }
}

Online-Store/OnlineStore.Cms/Views/StockEvent/Index.cshtml
@model IEnumerable<OnlineStore.Cms.Models.Response.Stock.StockEventRes>

@{
    ViewData["Title"] = "Stock Event";
}

<h1>STOCK EVENT</h1>

<form asp-controller="StockEvent" asp-action="Index">
    <p>
        Search: <input type="text" name="SearchString" />
        <input type="submit" value="Submit" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name Product
            </th>
            <th>
                Name Category
            </th>
            <th>
                Type
            </th>
            <th>
                Reason
            </th>
            <th>
                Quantity
            </th>
            <th>
                Time
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reason)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
            </tr>
        }
    </tbody>
</table>